version: '3'
services:
  proxy:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/ssl:/opt/ssl
      # - ./proxy/logs:/var/log/nginx
    restart: always
    networks:
      default:
        ipv4_address: 172.18.0.3

networks:
  default:
    external:
      name: wonknet