version: '3'
services:
  proxy:
    # image: nginx:latest
    image: nginx:1.18.0
    ports:
      - "443:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/ssl:/opt/ssl
      - .${NGINX_LOG_PATH}:/var/log/nginx
    restart: always
    networks:
      default:
        ipv4_address: 172.18.0.3

networks:
  default:
    external:
      name: wonknet
